pool:
  vmImage: Ubuntu-16.04

strategy:
  matrix:
    node_8_x:
      node_version: 8.x
    node_9_x:
      node_version: 9.x
    node_10_x:
      node_version: 10.x
    node_11_x:
      node_version: 11.x
    node_12_x:
      node_version: 12.x

steps:
  - task: NodeTool@0
    displayName: Install Node.js
    inputs:
      versionSpec: $(node_version)

  - script: yarn install --frozen-lockfile
    displayName: Install dependencies

  - script: yarn lint
    displayName: Lint source code

  - script: yarn prettier:check
    displayName: Check code format

  - script: yarn copy:paste:detector
    displayName: Copy/Paste detector

  - task: PublishPipelineArtifact@0
    displayName: Publish jscpd HTML report
    condition: failed()
    inputs:
      artifactName: 'CopyPasteDetectorReport'
      targetPath: 'target/jscpd-report.html'

  - script: yarn build
    displayName: Compile source code

  - script: npm run test:unit:ci
    displayName: Run unit tests

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: 'target/test-results.xml'
      testRunTitle: Test results for JavaScript
    condition: succeededOrFailed()

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: $(System.DefaultWorkingDirectory)/target/coverage/cobertura-coverage.xml
      reportDirectory: $(System.DefaultWorkingDirectory)/target/coverage
